apiVersion: v1
kind: Service
metadata:
  name: {{ include "wyoming-whisper.fullname" . }}
  labels:
    {{- include "wyoming-whisper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: wyoming-whisper
      protocol: TCP
      name: wyoming-whisper
  selector:
    {{- include "wyoming-whisper.selectorLabels" . | nindent 4 }}
